title: "Designer"
about_me: "Creative designer passionate about CAD modeling, architectural visualization, and detailed product development. My work bridges aesthetic design and functional precision, with a focus on clean geometry, efficient layouts, and real-world manufacturability. Whether shaping mechanical parts or visualizing interior spaces, I aim to deliver purposeful, high-impact designs."

